export const LOADING_API_DATA = 'LOADING_API_DATA';
export const LOADING_API_DATA_DONE = 'LOADING_API_DATA_DONE';
export const GET_API_DATA_SUCCESS = 'GET_API_DATA_SUCCESS';
export const GET_API_DATA_FAILURE = 'GET_API_DATA_FAILURE';
export const HANDLE_SEARCH = 'HANDLE_SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
